spring:
    profiles:
        include: oauth
        active: test

app:
    auth:
        tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
        tokenExpirationMsec: 8640000000
    oauth2:
        authorizedRedirectUris:
            - http://ec2-13-58-15-226.us-east-2.compute.amazonaws.com/login/callback

server:
    port: 8080

---
spring:
    profile: test

    h2:
        console:
            enabled: true
            path: /test_db
    datasource:
        hikari:
            # springboot 2.2.0 이상에서 MySQL5InnoDBDialect deprecated. 해당 설정 필요
            jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL

# spring 2.1.~ 에서 사용
#        url: jdbc:h2:mem:testdb
#        driver-class: org.h2.Driver
#        username: sa
#        password:
#        platform: h2
    jpa:
        show-sql: true
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.ddl-auto: create

#        database-platform: org.hibernate.dialect.H2Dialect
# spring 2.1.~ 에서 사용
#        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#        properties.hibernate.use_sql_comments: false

logging:
    level:
        org:
            hibernate:
                SQL: debug
